apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: gcr.io/google-samples/gb-frontend:v4
          ports:
            - containerPort: 80
          env: 
            - name: GET_HOSTS_FROM
              value: dns
